### ISSUE TITLE
I am sharing 'Veritcal Navigation Bar.docx' with you from WPS Office

### ISSUE THREAD

**Issue by SoeNyuntAung** [AaravRajSIngh/Chatbot#2]
WPS Office: Complete office suite with PDF editor

Here's the link to the file:
https://sg.docworkspace.com/d/sIP2g5e6nAfPMspcG

Get WPS Office for PC:
https://www.wps.com/d/?from=t

**Comment by AaravRajSIngh** [comment]
why so? 
Please contact Soe Nyunt Aung to share again or
apply for the access permission.

or sign in to an account with the access permission
